version: '3.5'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: thiago
      POSTGRES_PASSWORD: show1010
      POSTGRES_DB: test-api
    ports:
      - '5432:5432'
